---
- name: Add hummingbird user
  user:
    name: hummingbird
    createhome: no
    system: yes
- name: Install memcache
  apt:
    name: memcached
    state: present
  when: binary_only is not defined
- name: Configure memcached
  lineinfile:
    path: /etc/memcached.conf
    regexp: '^\-l'
    line: '-l {{ service_ip }}'
  when: binary_only is not defined
- name: Restart memcached
  service:
    enabled: yes
    name: memcached
    state: restarted
  when: binary_only is not defined
- name: Install curl
  apt:
    name: curl
    state: present
- name: Install jq
  apt:
    name: jq
    state: present
- name: Create download tmp dir
  tempfile:
    state: directory
  register: downloadtmpdir
  run_once: True
  delegate_to: localhost
- name: Change download perms
  file:
    path: "{{ downloadtmpdir.path }}"
    state: directory
    mode: 0755
  run_once: True
  delegate_to: localhost
- name: Find latest hummingbird binary
  shell: curl -s https://api.github.com/repos/troubling/hummingbird/releases/latest | jq --raw-output '.assets[0] | .browser_download_url'
  when: hummingbird_version == ''
  register: hummingbird_binary_url
  run_once: True
  delegate_to: localhost
- name: Download latest hummingbird binary
  command: wget {{ hummingbird_binary_url.stdout }}
  args:
    chdir: "{{downloadtmpdir.path}}"
  when: not hummingbird_binary_url|skipped
  run_once: True
  delegate_to: localhost
- name: Download latest dev hummingbird binary
  command: wget https://troubling.github.io/hummingbird/bin/hummingbird
  args:
    chdir: "{{downloadtmpdir.path}}"
  when: hummingbird_version == "dev"
  run_once: True
  delegate_to: localhost
- name: Download specific hummingbird binary
  command: wget https://github.com/troubling/hummingbird/releases/download/{{hummingbird_version}}/hummingbird
  args:
    chdir: "{{downloadtmpdir.path}}"
  when: hummingbird_version != "dev"
  run_once: True
  delegate_to: localhost
- name: Copy binary to node
  copy:
    src: "{{downloadtmpdir.path}}/hummingbird"
    dest: /usr/local/bin/hummingbird
    mode: 0755
    force: yes
- name: Create /etc/hummingbird
  file:
    path: /etc/hummingbird
    state: directory
    mode: 0755
    owner: hummingbird
    group: hummingbird
- name: Copy /etc/hummingbird/hummingbird.conf
  template:
    src: etc/hummingbird.conf.j2
    dest: /etc/hummingbird/hummingbird.conf
    mode: 0644
    owner: hummingbird
    group: hummingbird
- name: Create /var/cache/swift
  file:
    path: /var/cache/swift
    state: directory
    mode: 0755
    owner: hummingbird
    group: hummingbird
  when: binary_only is not defined
- name: Install rsyslog service
  package:
    name: rsyslog
    state: present
  when: binary_only is not defined
- name: Clean up /var/log/hummingbird (on reset)
  file:
    path: /var/log/hummingbird
    state: absent
  when:
    - binary_only is not defined
    - reset == "yes"
- name: Clean up /var/local/hummingbird/andrew.db (on reset)
  file:
    path: /var/local/hummingbird/andrew.db
    state: absent
  when:
    - binary_only is not defined
    - reset == "yes"
- name: Create /var/log/hummingbird
  file:
    path: /var/log/hummingbird
    state: directory
    mode: 0755
    owner: syslog
    group: adm
  when: binary_only is not defined
- name: Copy rsyslog config
  copy:
    src: rsyslog.d/20-hbird.conf
    dest: /etc/rsyslog.d/20-hbird.conf
    mode: 0644
  when: binary_only is not defined
- name: Install logrotate
  apt:
    name: logrotate
    state: present
  when: binary_only is not defined
- name: Copy logrotate config
  copy:
    src: logrotate.d/hummingbird
    dest: /etc/logrotate.d/hummingbird
    mode: 0644
  when: binary_only is not defined
- name: Restart rsyslog
  service:
    name: rsyslog
    enabled: yes
    state: restarted
  when: binary_only is not defined
- name: Create /var/run/hummingbird
  file:
    path: /var/run/hummingbird
    state: directory
    mode: 0755
    owner: hummingbird
    group: hummingbird
- name: create /srv/hummingbird
  file:
    path: /srv/hummingbird
    state: directory
    mode: 0755
    owner: hummingbird
    group: hummingbird
  when: binary_only is not defined
